server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
#  config:
#    import:
#      - "application_qa.yml.txt"
#      - "application_prod.yml.txt"
#  profiles:
#    active:
#      - "prod"
#  application:
#    name: cards
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
#
#build:
#  version: "1.0"
#
#cards:
#  message: "Welcome to Bank cards related local APIs"
#  contactDetails:
#    name: "Sagar Mahajan"
#    email: "2000sagarr@gmail.com"
#  onCallSupport:
#    - 1234567889
#    - 4352617273