server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
#  config:
#    import:
#      - "application_qa.yml.txt"
#      - "application_prod.yml.txt"
#  profiles:
#    active:
#      - "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
#loans:
#  message: "Welcome to Bank loans related local APIs"
#  contactDetails:
#    name: "Sagar Mahajan"
#    email: "2000sagarr@gmail.com"
#  onCallSupport:
#    - 1234567889
#    - 4352617273