build:
  version: "1.1"

accounts:
  message: "Welcome to Bank Account related QA APIs"
  contactDetails:
    name: "Sagar Mahajan-QA"
    email: "2000sagarr@gmail.com"
  onCallSupport:
    - 1234567889
    - 4352617273