build:
  version: "1.0"

cards:
  message: "Welcome to Bank cards related local APIs"
  contactDetails:
    name: "Sagar Mahajan"
    email: "2000sagarr@gmail.com"
  onCallSupport:
    - 1234567889
    - 4352617273