build:
  version: "1.2"

cards:
  message: "Welcome to Cards Account related Prod APIs"
  contactDetails:
    name: "Sagar Mahajan-Prod"
    email: "2000sagarr@gmail.com"
  onCallSupport:
    - 1234567889
    - 4352617273
    - 4352617273