build:
  version: "1.2"

loans:
  message: "Welcome to loans related Prod APIs"
  contactDetails:
    name: "Sagar Mahajan-Prod"
    email: "2000sagarr@gmail.com"
  onCallSupport:
    - 1234567889
    - 4352617273
    - 4352617273